name: fformaProj
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - lightgbm
  - pip
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - statsmodels
  - matplotlib
  - pip:
    # - absl-py==0.15.0
    # - antropy==0.1.4
    # - arch==5.0.1
    # - astunparse==1.6.3
    # - cachetools==4.2.4
    # - charset-normalizer==2.0.7
    # - colorama==0.4.4
    # - cycler==0.11.0
    # - flatbuffers==2.0
    # - fonttools==4.28.1
    # - gast==0.4.0
    # - google-auth==2.3.3
    # - google-auth-oauthlib==0.4.6
    # - google-pasta==0.2.0
    # - gpboost==0.6.7
    # - grpcio==1.41.1
    # - h5py==3.5.0
    # - idna==3.3
    # - joblib==1.1.0
    # - keras==2.7.0
    - keras-preprocessing==1.1.2
    # - kiwisolver==1.3.2
    # - libclang==12.0.0
    # - lightgbm==2.3.1
    # - llvmlite==0.37.0
    # - markdown==3.3.4
    # - matplotlib==3.3.1
    # - merf==1.0
    - natsort==7.1.1
    - nbeats-keras==1.5.0
    # - numba==0.54.1
    # - numpy==1.20.3
    # - oauthlib==3.1.1
    # - opt-einsum==3.3.0
    # - packaging==21.2
    # - pandas==1.3.4
    # - patsy==0.5.2
    # - pillow==8.4.0
    # - property-cached==1.6.4
    # - protobuf==3.19.1
    # - pyaml==21.10.1
    # - pyasn1==0.4.8
    # - pyasn1-modules==0.2.8
    # - pyparsing==2.4.7
    - python-dateutil==2.8.2
    # - pytz==2021.3
    # - pyyaml==6.0
    # - requests==2.26.0
    # - requests-oauthlib==1.3.0
    # - rsa==4.7.2
    - scikit-optimize==0.9.0
    # - six==1.16.0
    # - stochastic==0.6.0
    # - supersmoother==0.4
    # - termcolor==1.1.0
    # - threadpoolctl==3.0.0
    - tqdm==4.62.3
    - tsfeatures==0.3.1
    # - typing-extensions==3.10.0.2
    # - urllib3==1.26.7
    # - werkzeug==2.0.2
    # - wrapt==1.13.3
    - keras==2.9.0                
    - nvidia-ml-py==11.495.46
    - nvitop==0.6.2
    - pip==22.2.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-gpu==2.9.1
    - tensorflow-io-gcs-filesystem==0.26.0    
    